export { default as Footer } from "./Footer/Footer";
export { default as Header } from "./Header/Header";
export { default as Home } from "./Home/Home";
export { default as Products } from "./Products";
export { default as ProductsHome } from "./ProductsHome";
export { default as ProductDetails } from "./ProductDetails";
export { default as NotFound } from "./NotFound";
export { default as Cart } from "./Cart";
export { default as ProductCategory } from "./ProductCategory";
